#!/bin/bash


# Changes: convert to a running script
# Author:  Eric Herman <eric@freesa.org>
# Date:    Sun Jul 1 17:26:41 2012 +0200
#
#  enabled c++
#  extract the wget commands into separate script with updated versions
#  reference a SOURCES directory where the tarballs have placed
#  extract a PREFIX variable, default to installing in subdir of home for user
#  script will now halt if any command fails

PREFIX=$HOME/builds/avr
BUILD_DIR=/tmp/${USER}_avr_build
SOURCES=${PWD}/tarballs
PATCHES=${PWD}/patches

# avr-gcc toolchain build notes - version 1.2
# Last updated: January 9, 2010
# Matthew Beckler - matthew at mbeckler dot org
#
# Based on these guides:
# http://tuxgraphics.org/electronics/200901/avr-gcc-linux.shtml
# http://electrons.psychogenic.com/modules/arms/art/3/AVRGCCProgrammingGuide.php
# http://electrons.psychogenic.com/modules/arms/art/6/SimulatingandDebuggingAVRprograms.php
#
# Used a fresh install of Ubuntu 9.10 Karmic (i686) in a virtual machine.
#
# --------------------------------------------------------------------
#
# If you have the usr_local_avr_toolchain.tar.gz and want to install that and
# not go to all the trouble of building these tools, do this:
#
# cd /usr/local
# sudo tar xf ~/usr_local_avr_toolchain.tar.gz
#
# Be sure to add $PREFIX/bin to your path
# You probably want to install these to work with the wnl code:
# sudo apt-get install subversion scons python-pexpect

# general setup
rm -rf $BUILD_DIR
mkdir $BUILD_DIR
cd $BUILD_DIR

# add $PREFIX/bin to PATH, by adding this line to ~/.bashrc
export PATH=$PATH:$PREFIX/bin

# The texinfo package is used while building binutils.
# sudo apt-get install texinfo

# binutils-2.26
tar xf ${SOURCES}/binutils-*.tar.* &&
pushd binutils-* &&
mkdir build-binutils &&
cd build-binutils &&
export CC=gcc &&
../configure \
  --target=avr \
  --prefix=$PREFIX \
  --disable-nsl \
  --enable-install-libbfd \
  --disable-werror &&
make &&
make install &&
popd &&

# to test binutils installation:
$PREFIX/bin/avr-as --help &&


# gcc-6.1.0 requires gmp, mpfr, and mpc
tar xf ${SOURCES}/gcc-*.tar.* &&
tar xf ${SOURCES}/gmp-*.tar.* &&
mv -v gmp-* gmp &&
mv -v gmp ./gcc-*/ &&
tar xf ${SOURCES}/mpfr-*.tar.* &&
mv -v mpfr-* mpfr &&
mv -v mpfr ./gcc-*/ &&
tar xf ${SOURCES}/mpc-*.tar.* &&
mv -v mpc-* mpc &&
mv -v mpc ./gcc-*/ &&
pushd gcc-* &&
mkdir build-gcc &&
cd build-gcc &&
../configure \
  --target=avr \
  --prefix=$PREFIX \
  --disable-nsl \
  --enable-languages=c,c++ \
  --disable-libssp &&
make &&
# sometimes there are PATH issues with "make install",
# so you might try "sudo su" and then "make install".
# be sure to 'exit' from the root account before continuing!
make install &&
popd &&

# to test:
avr-gcc --version &&

# avr-libc-2.0.0
tar xf ${SOURCES}/avr-libc-*.tar.* &&
pushd avr-libc-* &&
mkdir build-avr-libc &&
cd build-avr-libc &&
export CC=avr-gcc &&
../configure \
  --build=`../config.guess` \
  --host=avr \
  --prefix=$PREFIX &&
make &&
# again, it might work best to "sudo su" then "make install"
# be sure to 'exit' from the root account before continuing!
make install &&
popd &&

# avrdude-6.3
# sudo apt-get install flex byacc libusb-dev
tar xf ${SOURCES}/avrdude-*.tar.* &&
pushd avrdude-* &&
export CC=gcc &&
./configure \
  --prefix=$PREFIX &&
make &&
make install &&
export CC= &&
# TODO add udev magic to fix usb permissions for non-root user using avrdude.
popd &&

# gdb-7.11
# sudo apt-get install libncurses5-dev
# the above install fixes a warning about "no termcap library found"
tar xf ${SOURCES}/gdb-*.tar.* &&
pushd gdb-* &&
./configure \
  --target=avr \
  --prefix=$PREFIX \
  --disable-werror
make &&
make install &&
popd &&

# simulavr-1.0.0
# sudo apt-get install tcl-dev cvs autoconf libtool swig g++ zlib1g-dev
tar xf ${SOURCES}/simulavr*.tar.* &&
pushd simulavr* &&
./bootstrap &&
./configure \
  --prefix=$PREFIX \
  --with-bfd=$PREFIX &&
# remove both references to 'examples' in the Makefile.
patch -Np1 -i ${PATCHES}/simulavr-remove-examples.patch &&
patch -Np1 -i ${PATCHES}/simulavr-1.0.0-fix-resize-1.patch &&
make &&
make install &&
popd &&

echo "YAY"

